import { SCard,SAvatar,SBadge, SIcon, SText } from "../../modules/surrealism-ui/index.slint";
import { Themes,UseSurrealismFn,ColorLevel } from "../../modules/surrealism-ui/use/index.slint";
import { ROOT-GLOBAL } from "../../global.slint";
import { SButton } from "../../modules/surrealism-ui/src/button/index.slint";
export component ListWindow inherits Rectangle{
    VerticalLayout {
        width: 100%;
        alignment: space-between;
        header:= SCard {
            height: 46px;
            background: ROOT-GLOBAL.theme-color-list;
            border-type: None;
            width: 100%;
            SButton {
                background: #1E1F22;
                padding-type: Small;
                font-size: 12px;
                text: "寻找或开始新的对话";
                font-weight: 700;
                width: 90%;
                border-type: None;
            }
        }
        center:= Rectangle {
            height: parent.height - header.height - footer.height;
            VerticalLayout {
                alignment: start;
                spacing: 4px;
                for item in 5: SCard{
                    width: parent.width;
                    border-type: None;
                    background: ROOT-GLOBAL.theme-color-list;
                    height: 60px;
                    HorizontalLayout {
                        Rectangle {
                            width: 48px;
                            SIcon {
                                source: @image-url("../../assets/avatar.png");
                                height: 24px;
                                width: 24px;
                            }
                        }
                        Rectangle {
                            width: parent.width - 48px;
                            SText {
                                x: 0;
                                text: "Willins.Sheng";
                            }
                        }
                    }
                }
            }
        }
        footer:= SCard {
            height: 46px;
            background: #232428;
            border-type: None;
            width: 100%;
            HorizontalLayout {
                alignment: space-between;
                Rectangle {
                    width: 60px;
                    Rectangle {
                        height: avatar.height;
                        width: avatar.width;
                        avatar:= SAvatar {
                            height: 36px;
                            width: 36px;
                            avatar-size: 24px;
                            avatar: @image-url("../../assets/avatar.png");
                        }
                        SBadge {
                            height: 12px;
                            width: 12px;
                            theme: Success;
                            x: self.get-x(avatar.width);
                            y: self.get-y(avatar.height);
                            position: RightBottom;
                            clip: true;
                            icon: @image-url("");
                        }
                    }
                }
                Rectangle {
                    clip: true;
                    SText {
                        width: parent.width;
                        wrap: no-wrap;
                        text: "Willins.Sheng";
                    }
                }
                HorizontalLayout {
                    width: 45%;
                    alignment: space-around;
                    Rectangle {
                        SIcon {
                            private property <bool> is-close: false;
                            height: 18px;
                            width: 18px;
                            colorize: self.get-colorize();
                            source: @image-url("../../assets/Voice-2.svg");
                            clicked => {
                                is-close = !is-close;
                                if is-close{
                                    self.source = @image-url("../../assets/Voice-4.svg");
                                    self.colorize = #F23F42;
                                }else{
                                    self.source = @image-url("../../assets/Voice-2.svg");
                                    self.colorize = UseSurrealismFn.get-color-dark(ColorLevel.Font);
                                }
                            }
                        }
                        
                    }
                    Rectangle {
                        SIcon {
                            height: 18px;
                            width: 18px;
                            colorize: self.get-colorize();
                            source: @image-url("../../assets/earphone.svg");
                        }
                    }
                    Rectangle {
                        SIcon {
                            height: 18px;
                            width: 18px;
                            colorize: self.get-colorize();
                            source: @image-url("../../assets/set.svg");
                        }
                    }
                }
            }
        }
    }
}